### ISSUE TITLE
top100 and more?

### ISSUE THREAD

**Issue by mabt** [Talljoe/crytrac#2]
Hello,

Thanks for this awesome tool!

The cryptocurrencies that are not content in the top100 of coinmarketcap.com are not displayed.

"Unknown coin:DNT
Unknown coin:RCN..."

It would be difficult to add the others pages?

Best Regards,
Maxime.

**Comment by Talljoe** [comment]
Fixed. da4cc40cef312208f084d9f4b1ec184e41f14d4a

CMC changed their API a little bit ago and only return the top coins by default.
